### ISSUE TITLE
player is able to choose cell even after initial config.

### ISSUE THREAD

**Issue by Nazi-pikachu** [pathakshashank17/Conways-Game-of-Life-JS#1]
Player is able to choose a cell even after choosing the initial configuration while what should happen that the player should not been able to choose a cell after the initial configuration.For better understanding play the game with an inital configuration then try  to click on the grid near the cells.
PS:- I donot know much about the conways game of life so i leave it to you to determine whether this is a bug or a feature :).

**Comment by pathakshashank17** [comment]
Yes! You are absolutely right, it was initially a bug 😅, but I chose not to resolve it as it adds interactivity to the grid. Due to that, users can modify configuration mid-generation and watch the results. I hope this makes sense as to why I left the bug. Thanks for bringing this up 🙌.
